version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: roda_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roda724
      POSTGRES_DB: roda_db
    volumes:
      - ./roda_schema.sql:/docker-entrypoint-initdb.d/roda_schema.sql:ro
      - ./seed:/docker-entrypoint-initdb.d  
    networks:
      - roda-network

  backend:
    build: .
    container_name: roda_backend
    ports:
      - "5000:5000"

    env_file:
    - .env
    environment:
      DB_USER: postgres
      DB_PASSWORD: roda724
      DB_NAME: roda_db
      DB_HOST: postgres-db
      DB_PORT: 5432
      JWT_SECRET_KEY: supersecretjwtkey
      JWT_ACCESS_TOKEN_EXPIRES: 3600
      FLASK_ENV: development
    depends_on:
      - postgres-db
    networks:
      - roda-network

networks:
  roda-network:
    driver: bridge
